# Generated by Django 3.0.6 on 2020-05-24 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='static',
            new_name='status',
        ),
    ]
